# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171114_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
