# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_client_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
